### ISSUE TITLE
The package could not be installed.

### ISSUE THREAD

**Issue by AlainMelsens** [burlingtonbytes/wp-blockade-section-block#1]
Dear,
I have tried to install this little Blockade "wp-blockade-section-block" plugin, but it's not working.
I have some experiences with WordPress, so, I tried it the normal way, by using the "Plugins" menu followed by "Add New" and "Upload Plugin". 
Then I received an error: "**The package could not be installed. No valid plugins were found.**". :(
Even when I try it by manualy copying the files off the master folder under the wp-content/plugins folder, I can't see the plugin, so I can't activate either.
What do I wrong or could you tell me how to install or using this Blockade plugin, please?
I use WordPress version 4.7.4. with PHP version 7.1.1. (64bit)
Thanks in advance.
Best Regards,
Alain Melsens

**Comment by gschoppe** [comment]
section-block isn't a WordPress plugin, it is an example of a per-theme addon for Blockade. The easiest way to install it is to create a folder within your theme named "blockade", and a subfolder within that, named "section-block".  Then just place the files in this repository into the "section-block" folder.

It is possible to bundle addons into traditional plugins by creating a loader plugin that uses the filter `wp-blockade-register-addon-dir` to register a new directory for blockade to search for addons in, within the plugin directory, but that is beyond the scope of this simplified example block type.

**Comment by AlainMelsens** [comment]
Hello,
Thanks for your fast response.
I use also a child theme, so I saw, that it must be installed in the parent theme folder otherwise it doesn't work either.
Now it's working fine. Thanks again for your fast support.
And sorry for the misunderstanding about installing theme plugins. This was new for me.
Best Regards,
Alain Melsens

**Comment by gschoppe** [comment]
The lack of support for child themes was actually an oversight in this particular addon's code. It should now work in the child theme, which is a much better option for installing.
